backend:
  name: github
  repo: yambal/Gatsby-Starter-2021
  branch: cms/NetlifyCms

# メディアがアップロードされるディレクトリのPath
media_folder: /static/images

# メディアがアップロードされるディレクトリの相対Path
# であるべきだが、MDにはルートからのパスを記述し、onCreateNode で処理する
# Netlify CMS では 画像への相対パス反映に対応していないが
# Gatsby の gatsby-remark-images は 相対パスでしか処理できないため
public_folder: /static/images
  
collections:
  - name: Index
    label: TopPage
    folder: src/pages/
    create: false
    slug: "index"
    fields:
      - { label: "Template Key", name: "template", widget: "hidden", default: "TemplateIndex"}
      - { label: '本文', name: body, widget: markdown }
  - name: post
    label: Posts
    folder: src/pages/
    create: true
    slug: 
      ncoding: "ascii"
      clean_accents: true
      sanitize_replacement: "_"
    fields:
      - { label: "Template Key", name: "template", widget: "hidden", default: "TemplatePage"}
      - { label: 'タイトル', name: title }
      - { label: 'ヘッダー画像', name: 'feature_image', widget: 'image'}
      - { label: 'グローバルメニュー', name: 'global_navi', widget: 'select', options:
        - { label: "表示しない", value: -1 }
        - { label: "位置 1", value: 1 }
        - { label: "位置 2", value: 2 }
        - { label: "位置 3", value: 3 }
        - { label: "位置 4", value: 4 }
        - { label: "位置 5", value: 5 }
      - { label: '本文', name: body, widget: markdown }
  - name: post
    label: Posts
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "template", widget: "hidden", default: "TemplatePost"}
      - { label: '日付',name: date,  widget: datetime }
      - { label: 'タイトル', name: title }
      - { label: 'ヘッダー画像', name: 'feature_image', widget: 'image'}
      - { label: '本文', name: body, widget: markdown }