backend:
  name: github
  repo: yambal/Gatsby-Starter-2021
  branch: cms/NetlifyCms

# メディアがアップロードされるディレクトリのPath
media_folder: /static/images

# メディアがアップロードされるディレクトリの相対Path
# MD に記載されるpathは、これに画像ファイル名が連結される
# MD に記載される画像Pathが相対パスでしか処理されない
public_folder: /static/images
  
collections:
  - name: post
    label: Posts
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "template", widget: "hidden", default: "TemplatePost"}
      - { label: '日付',name: date,  widget: datetime }
      - { label: 'タイトル', name: title }
      - { label: 'ヘッダー画像', name: 'feature_image', widget: 'image'}
      - { label: '本文', name: body, widget: markdown }